export const BROWN_HISTORY = [
  { id: 69, date: "2026-01-28 23:12", content: "[기능] 오더 관리 고도화: 분실물 상세 표시, 오더 삭제→취소로 변경, 입고 파트너 탁송 정보 추가, 검색 기준 용어 수정", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 68, date: "2026-01-28 18:27", content: "[정책] 오더 상태 전이 정책 개편: 파트너 유형 무관 통일된 4단계 흐름 (발행→예약→수행 중→완료) 적용", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 67, date: "2026-01-28 10:13", content: "[문서] 오더 관리 기능 명세서 고도화: 운영 시나리오 구체화, 점검 항목 전체 목록", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 66, date: "2026-01-26 16:45", content: "미션 정책 관리 - 할당된 차량 검색 기능 및 목업 데이터 추가", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 65, date: "2026-01-23 17:09", content: "오더 관리 목업 데이터 외부 파일 분리 및 200개로 증량, 필터 기본값 1개월로 변경", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 64, date: "2026-01-23 14:06", content: "[기능] 미션 관리 - 상태(활성/비활성) 추가", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 63, date: "2026-01-23 13:26", content: "[정책] 미션 관리 기능 정책 변경", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 62, date: "2026-01-23 11:15", content: "[정책] 오더별 수행 목업, 발행 유형별 수행(사진 촬영, 점검) 기능명세 작성", isPolicyChange: true, links: [{ label: "오더별 수행 목업", page: "checklist-mockup" }] },
  { id: 61, date: "2026-01-20 14:30", content: "[기능] 분실물 관리: 검색/필터, UI 일관성 및 상세화면 동작 개선", isPolicyChange: true, links: [{ label: "분실물 관리", page: "lostfound" }] },
  { id: 60, date: "2026-01-20 11:12", content: "[기능] 관제 대시보드 구현 방향 안내 모달 레이어 추가", isPolicyChange: false, links: [] },
  { id: 59, date: "2026-01-20 09:30", content: "[기능] URL 쿼리 스트링 양방향 동기화 적용 및 페이지별 피드백 로딩 로직 고도화 (Deep Linking 지원)", isPolicyChange: false, links: [] },
  { id: 58, date: "2026-01-19 17:30", content: "[UI] 대시보드 문구 및 노출 필요한 정보 요소 변경", isPolicyChange: true, links: [{ label: "대시보드", page: "dashboard" }] },
  { id: 57, date: "2026-01-19 17:30", content: "[고도화] 피드백 작성자 정보 상시 노출, 해결 컨펌 추가", isPolicyChange: false, links: [] },
  { id: 56, date: "2026-01-19 12:28", content: "[기능] QnA 댓글(피드백) 입력 기능 추가", isPolicyChange: true, links: [] },
  { id: 55, date: "2026-01-16 13:04", content: "[UI/UX] 주요 Drawer 하이브리드 레이아웃 적용: 데스크톱 너비 조절 기능 복구 및 모바일 반응형 최적화", isPolicyChange: false, links: [] },
  { id: 54, date: "2026-01-16 12:23", content: "[리팩토링] App.jsx 비대화 해결 완료: 모든 페이지 분리", isPolicyChange: false, links: [] },
  { id: 53, date: "2026-01-16 12:10", content: "[UI/UX] 오더 관리: 상세 Drawer 내 지역(지역1, 2) 및 일시(발행, 수행) 정보 추가", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 52, date: "2026-01-16 11:45", content: "[기능/UI] 오더 관리: 검색 필터 레이블 개선 및 테이블 컬럼 확장 (지역, 일시 정보 추가)", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 51, date: "2026-01-15 22:14", content: "[기능] 오더 수동 발행 기능 고도화: 차량 번호 유효성 체크 및 차량 기본정보 조회", isPolicyChange: true, links:  [{ label: "오더 관리", page: "orders" }] },
  { id: 50, date: "2026-01-15 21:59", content: "[기능] 오더 수동 발행 기능 고도화: 발행 옵션(오더 구분/유형) 선택 기능 추가", isPolicyChange: true, links:  [{ label: "오더 관리", page: "orders" }] },
  { id: 49, date: "2026-01-15 21:20", content: "[버그수정] 모바일 브라우저 초기 DIM 중첩 현상 해결 및 레이아웃 z-index 최적화", isPolicyChange: false, links: [] },
  { id: 48, date: "2026-01-15 18:27", content: "[Hotfix] 검색 필터 UI 스타일 충돌 수정: Select/Input 너비 강제 적용 (!important)", isPolicyChange: false, links: [] },
  { id: 47, date: "2026-01-15 18:25", content: "[UI/버그수정] 검색 필터 레이아웃 중첩 문제 해결 및 카테고리별 검색 UI 정교화", isPolicyChange: false, links: [] },
  { id: 46, date: "2026-01-15 18:23", content: "[시스템] 담당자 정보 간소화(상태 제거/삭제 추가), CMS 외부 링크 연동 및 청구서 엑셀 다운로드 기능 추가", isPolicyChange: false, links: [{ label: "담당자 조회", page: "partner-managers" }, { label: "청구 관리", page: "billing" }] },
  { id: 45, date: "2026-01-15 18:20", content: "[정책] 단가 관리 기능을 파트너 상세 정보로 통합 및 CRUD 기능 구현", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 44, date: "2026-01-15 18:17", content: "[고도화] 미션 관리: 일괄 삭제 시 사유 입력 모달 적용 (Audit Log 강화)", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 43, date: "2026-01-15 18:14", content: "[기능] 미션 관리: 미션 일괄 선택 삭제 기능 도입", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 42, date: "2026-01-15 18:10", content: "[UI] 검색 카테고리 필터 도입 및 테이블 정렬 기능 전사 적용", isPolicyChange: false, links: [] },
  { id: 41, date: "2026-01-15 18:09", content: "[고도화] 검색 UI 표준화, 단가 정책 파트너 통합 및 미션 벌크 삭제 기능 도입", isPolicyChange: false, links: [] },
  { id: 40, date: "2026-01-15 15:20", content: "[Hotfix] 파트너 관리 페이지 파일 누락 수정 (PartnersPage.jsx 생성)", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 39, date: "2026-01-15 15:15", content: "[버그수정] 파트너 관리 컴포넌트 경로 정상화 및 신규 재구현 기능 UI 연동 완료", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 38, date: "2026-01-15 15:06", content: "[기능] 파트너 관리 고도화: 필드 명칭 표준화(파트너 명) 및 신규 등록/수정 기능 구현, UI 불필요 항목 제거", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 37, date: "2026-01-15 14:53", content: "[기능] 파트너 관리 재구현: 상세 계약 정보 및 대규모 존 배정(지역정보 병기) 기능 적용", isPolicyChange: true, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 36, date: "2026-01-15 14:38", content: "[기능] 담당자/수행원 조회: 파트너사별 인력 현황 및 존 배정 모니터링 기능 구현", isPolicyChange: false, links: [{ label: "담당자 조회", page: "partner-managers" }, { label: "수행원 조회", page: "workers" }] },
  { id: 35, date: "2026-01-15 14:36", content: "[기능] 파트너 관리: 파트너사 등록/수정 및 복수 지역(Zone) 할당 로직 구현", isPolicyChange: false, links: [{ label: "파트너 관리", page: "partners" }] },
  { id: 34, date: "2026-01-15 14:32", content: "[UI] LNB 메뉴 그룹 동작 표준화: 오더 정책 및 업무 관리 그룹 아코디언 기능 적용", isPolicyChange: false, links: [] },
  { id: 33, date: "2026-01-15 14:15", content: "[UI] 사이드바(LNB) 내부 스크롤 적용 및 스크롤바 UI 숨김 처리", isPolicyChange: false, links: [] },
  { id: 32, date: "2026-01-15 13:30", content: "[UI] Drawer 닫기 버튼 스타일 조정: 배경 제거 및 Hover 효과 유지", isPolicyChange: false, links: [] },
  { id: 31, date: "2026-01-15 13:25", content: "[UI] 업데이트 이력 내 '제품 정책 변경' 건 선별 필터 기능 추가", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 30, date: "2026-01-15 13:20", content: "[시스템] 빌드 파이프라인 최적화: prebuild 스크립트를 통한 version.json 자동 갱신 로직 적용", isPolicyChange: false, links: [] },
  { id: 29, date: "2026-01-15 13:10", content: "[시스템] 전사 리스트 화면 페이지네이션(40개 단위) 도입 및 데이터 로딩 최적화", isPolicyChange: false, links: [] },
  { id: 28, date: "2026-01-15 13:05", content: "[정책] 미션별 금액 산정 기능 도입 및 수행 증빙 사진 필수 옵션 기본값 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 27, date: "2026-01-15 12:15", content: "[시스템] 업데이트 이력 관리 이원화(브라운/아스티) 및 외부 파일 연동, 버전 체크 로직 최적화", isPolicyChange: true, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 26, date: "2026-01-15 09:15", content: "[시스템] 모바일 반응형 레이아웃 대응: 햄버거 메뉴 및 사이드바 드로어 구현", isPolicyChange: false, links: [] },
  { id: 25, date: "2026-01-15 09:10", content: "[시스템] Vercel 트랜잭션 최적화: 업무시간 외 체크 제한 및 활동 기반 버전 업데이트 로직 고도화", isPolicyChange: false, links: [] },
  { id: 24, date: "2026-01-15 08:50", content: "[시스템] 실시간 버전 업데이트 감지 및 브라우저 캐시 무효화 기능 구현", isPolicyChange: false, links: [] },
  { id: 23, date: "2026-01-14 18:10", content: "미션 상세 화면 내 수행 증빙 사진 필수 여부 정보 노출", isPolicyChange: false, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 22, date: "2026-01-14 18:00", content: "[정책] 미션 등록 시 차량 번호 일괄 입력(최대 1,000건) 및 수행 증빙 사진 촬영 옵션 도입", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 21, date: "2026-01-14 17:40", content: "[정책] 미션 관리 내 차량 상세 정보(차종/지역) 연동 및 다차원 필터링 기능 강화", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 20, date: "2026-01-14 16:30", content: "[정책] 세차 유형 옵션 정렬 기준 변경(내외부 우선) 및 미사용 옵션(물세차) 제거", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 19, date: "2026-01-14 16:25", content: "[정책] LNB 메뉴 순서 변경(미션 관리 하향 조정) 및 수행완료 미션 삭제 제한 정책 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }] },
  { id: 18, date: "2026-01-14 16:16", content: "[정책] 필드 순서 표준화(오더 구분/유형/세차 유형) 및 미션-오더 연동 상세 로직 고도화", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }, { label: "오더 관리", page: "orders" }] },
  { id: 17, date: "2026-01-14 16:01", content: "업데이트 이력 시간 기록 규칙 확정 (KST 16:01 기준) 및 기존 이력 시간 교정", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 16, date: "2026-01-14 15:50", content: "[정책] 관리자-수행원 간 정보 관심사 분리 정책에 따라 어드민 내 현장 가이드 및 유종 정보 전면 제거", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 15, date: "2026-01-14 15:40", content: "[정책] 세차 업무 무관 정보(유종) 제거 및 충전보장형 차량 대상 특수 반납 가이드 노출 정책 적용", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 14, date: "2026-01-14 15:25", content: "[정책] 세차 대상 차량 기준(sharing_type) 정의 및 진행중 오더의 실시간 상태 노출 로직 적용", isPolicyChange: true, links: [{ label: "차량 관리", page: "vehicles" }] },
  { id: 13, date: "2026-01-14 15:10", content: "[정책] 업데이트 이력 관리 체계 개편: 제품 정책 변경 여부 식별 및 기록 의무화", isPolicyChange: true, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 12, date: "2026-01-14 14:50", content: "디자인 가이드(PNG) 분석 기반 UI 컴포넌트 스타일 고도화 및 디자인 토큰 반영", isPolicyChange: false, links: [{ label: "차량 관리", page: "vehicles" }, { label: "오더 관리", page: "orders" }] },
  { id: 11, date: "2026-01-14 14:35", content: "업데이트 이력 자동 기록 규칙 최종 수정 (실시간 KST 반영) 및 UI 점검", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 10, date: "2026-01-14 14:30", content: "업데이트 이력 데이터 구조 개선(링크 추가) 및 UI 컬럼 반영", isPolicyChange: false, links: [{ label: "업데이트 이력", page: "update-history" }] },
  { id: 9, date: "2026-01-13 18:40", content: "[정책] 미션 삭제 시 사유 입력 강제 및 감사 로그 기록 정책 적용", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }, { label: "오더 관리", page: "orders" }] },
  { id: 8, date: "2026-01-13 18:25", content: "[정책] 세차 오더-미션 간 상태 라이프사이클 동기화 로직 정의", isPolicyChange: true, links: [{ label: "미션 관리", page: "missions" }, { label: "오더 관리", page: "orders" }] },
  { id: 7, date: "2026-01-13 18:15", content: "[정책] 파트너 유형별(현장/입고) 프로세스 분리에 따른 진행 상태 선택값 제한 규칙 적용", isPolicyChange: true, links: [{ label: "오더 관리", page: "orders" }] },
  { id: 6, date: "2026-01-13 18:10", content: "차량 상세 내 모든 세차 이력 항목에 대해 오더 상세 Drawer 자동 연결 기능 보완", isPolicyChange: false, links: [{ label: "차량 관리", page: "vehicles" }, { label: "오더 관리", page: "orders" }] },
  { id: 5, date: "2026-01-13 17:55", content: "차량 상세 세차 이력 클릭 시 새 창에서 오더 상세 자동 연결 기능 구현", isPolicyChange: false, links: [{ label: "차량 관리", page: "vehicles" }, { label: "오더 관리", page: "orders" }] },
  { id: 4, date: "2026-01-13 17:37", content: "업데이트 이력 페이지 UI 개선 (헤더 명칭 변경) 및 자동 기록 규칙 적용", isPolicyChange: false, links: [] },
  { id: 3, date: "2026-01-13 17:25", content: "업데이트 이력 ID 컬럼 추가 및 정렬, 사이드바 스크롤바 숨김 처리", isPolicyChange: false, links: [] },
  { id: 2, date: "2026-01-13 16:57", content: "전체 용어 및 데이터 표기 형식 표준화 (차량 번호, 존 이름, 파트너 명 등)", isPolicyChange: false, links: [] },
  { id: 1, date: "2026-01-13 15:53", content: "기능 명세(Markdown) Drawer 연동 및 렌더러 구현", isPolicyChange: false, links: [] },
];

export const ASTI_HISTORY = [
  { id: 3, date: "2026-01-20 13:22", content: "발행 유형정책관리", isPolicyChange: false, links: [] },
  { id: 2, date: "2026-01-20 13:22", content: "정책관리 페이지 업데이트(AI정책관리, 존정책관리)", isPolicyChange: false, links: [] },
  { id: 1, date: "2026-01-20 13:21", content: "ASTI 업데이트 이력 기록 시작", isPolicyChange: false, links: [] },
];